### ISSUE TITLE
High CPU and GPU usage when dialogue editor displays nothing

### ISSUE THREAD

**Issue by LanKuDot** [JosephBarber96/UnityDialogueEditor#2]
When dialogue editor displays the conversion content, the cpu and gpu usage is normal. But if I select the other gameobject and dialogue editor displays nothing, the cpu and gpu usage is quite high.

**Comment by LanKuDot** [comment]
About this issue, it seems that it could be fixed by removing [this line of code](https://github.com/JosephBarber96/UnityDialogueEditor/blob/master/DialogueEditor/Assets/DialogueEditor/Assets/Scripts/Editor/DialogueEditorWindow.cs#L434). The editor also draws nothing in the node editing panel when there is no conversation asset selected.

**Comment by JosephBarber96** [comment]
I have now fixed this in f2c800bc8e49ac557ba8f5618c268edc0efdb611 - thanks!
