### ISSUE TITLE
Allow option nodes to trigger events when selected

### ISSUE THREAD

**Issue by ecameracci** [JosephBarber96/UnityDialogueEditor#4]
I have a scenario where I use the NPC conversation to confirm or deny whether to change scenes, but selecting the 'Yes' option needs to connect to a speech node in order to trigger the event to change scenes. This means there is an empty conversation window shown before changing scenes.

![image](https://user-images.githubusercontent.com/6487711/122306136-efb67480-ced5-11eb-813f-dc6ffb1b4e26.png)

Would it make sense to also have events triggered on selecting option nodes in order to avoid using a speech node?

**Comment by JosephBarber96** [comment]
This seems like it would be a great addition - I will look at implementing this in a future update.

**Comment by JosephBarber96** [comment]
This change has been made and pushed to the master/main branch. After some further testing, if no issues are found, I will submit this update to the Unity Asset store as a minor version update.

**Comment by ecameracci** [comment]
Got the chance to test this myself and didn't notice any issues. Thanks for the quick response and update to this!

**Comment by JosephBarber96** [comment]
This update is now live on the Unity Asset store
